### PR TITLE
Updated description

### PR DESCRIPTION
**Pull request by ChristophSchranz**
The functionality is the same.

### CODE REVIEW

**Comment by foosel** [comment]
I've rolled back the change to the publication date. Please do not change that on updates - it's the *publication* date after all ;)

**Comment by ChristophSchranz** [comment]
Thanks @foosel 
Just one more question: How is it possible to update the description in https://plugins.octoprint.org/plugins/preprintservice/ ?

I've updated the README.md /extras/preprintserver.md in the Plugin-repo, and the preprintserver.md this repo. However, the description published on plugins.octoprint.org is from the previous release.

**Comment by foosel** [comment]
Hm... could be that the build didn't properly run through, that wouldn't be the first time. I'll try to tickle it into action

**Comment by foosel** [comment]
There we go. Should be fine now.

**Pull request merged**
