### PR TITLE
Added the redeem plugin

### PR DESCRIPTION
**Pull request by eliasbakken**

### CODE REVIEW

**Comment by foosel** [comment]
@eliasbakken It's a bit embarrassing but I only noticed just now that you didn't specify an archive URL, making this plugin uninstallable through the plugin manager built into OctoPrint. Was this intentional or should I set this to `https://github.com/eliasbakken/octoprint_redeem/archive/master.zip`?

**Comment by eliasbakken** [comment]
Yes, please do! I had forgotten about it completely, but it would be great to have this searchable.

**Comment by foosel** [comment]
@eliasbakken done

**Comment by foosel** [comment]
@eliasbakken The CI build for the repository is currently failing a check because it the external images from this plugin throw a 401 - any ETA when the server will be back in shape? Alternatively - could you maybe send an update that hosts the relevant images on the repository itself?

**Comment by eliasbakken** [comment]
The server should be back up. I'll see if there is a way to host any images
somewhere else...

**Comment by foosel** [comment]
Perfect, thanks for getting back to me! Re hosting, you could just drop the plugin's related images into `/assets/img/plugins/redeem` here on the repo (via PR). Or I can do it too.

**Pull request merged**
