### PR TITLE
Added nexus_ai plugin

### PR DESCRIPTION
**Pull request by fiber-punk**

### CODE REVIEW

**Review by jneilliii — CHANGES_REQUESTED** [review]
seems none of my comments from #1109 have been addressed.

**Comment by jneilliii** [comment]
@fiber-punk you still haven't addressed the issues on your plugin's repository. You need to change `fiberpunk` to `fiberpunk1` [here](https://github.com/fiberpunk1/OctoPrint-Nexus-AI/blob/master/octoprint_nexus_ai/__init__.py#L165).

**Review by jneilliii — CHANGES_REQUESTED** [review]
@fiber-punk you still haven't addressed the issues on your plugin's repository. You need to change `fiberpunk` to `fiberpunk1` [here](https://github.com/fiberpunk1/OctoPrint-Nexus-AI/blob/master/octoprint_nexus_ai/__init__.py#L165).

**Comment by fiber-punk** [comment]
I have fixed the user from "fiberpunk" to "fiberpunk1"

**Review by jneilliii — APPROVED** [review]

**Pull request merged**
