### PR TITLE
Added PCA9685 hardware PWM support over I2C for LED lighting

### PR DESCRIPTION
**Pull request by ozgunawesome**
PCA9685 can control 16 separate PWM channels with 12 bit resolution (4096 steps) and connects over I2C. Breakout boards such as [this](https://www.adafruit.com/product/815) are available. 

My implementation only uses 4 channels (R/G/B/W) though. It responds to the `M150` gcode. Forked from [google/OctoPrint-LEDStripControl](https://github.com/google/OctoPrint-LEDStripControl). I use it for my Ender 3 lighting rig.

### CODE REVIEW

**Comment by foosel** [comment]
Hi @ozgunawesome, nice plugin! 👍 

I took a quick look at the source and noticed that your plugin has the identifier `PCA9685LEDStripControl` but registers its update mechanism under `ledstripcontrol`. Those two should definitely match so there are no conflicts with other plugins out there.

Could you fix that and give me a ping here so I can merge this? Cheers!

**Comment by ozgunawesome** [comment]
@foosel changed that dictionary name and updated the version number!

**Comment by zombie-repellent** [comment]
@ozgunawesome I have installed this plugin but its not showing up in my list of plugins. I've tried to reinstall it and still no luck

**Comment by ozgunawesome** [comment]
> @ozgunawesome I have installed this plugin but its not showing up in my list of plugins. I've tried to reinstall it and still no luck

Have you restarted OctoPrint after installing the plugin?

**Comment by zombie-repellent** [comment]
> > @ozgunawesome I have installed this plugin but its not showing up in my list of plugins. I've tried to reinstall it and still no luck
> 
> Have you restarted OctoPrint after installing the plugin?

Yes I always restart octoprint after installing with no luck

**Pull request merged**
