### PR TITLE
Add PSUControl-RPi.GPIO

### PR DESCRIPTION
**Pull request by kantlivelong**

### CODE REVIEW

**Comment by jneilliii** [comment]
No software update hook?

**Comment by kantlivelong** [comment]
Good catch. Fixed

**Comment by jneilliii** [comment]
Doesn't the dictionary returned need to match the plugin_identifier [here](https://github.com/kantlivelong/OctoPrint-PSUControl-RPiGPIO/blob/02f5dbb3940b3a10c0b975cfa3fb0cbf9938c1bd/octoprint_psucontrol_rpigpio/__init__.py#L232). Should be `psucontrol_rpigpio`? Also, do you want to coordinate the release with the 1.0,0 version of PSUControl or have this merged in ahead of time?

**Comment by kantlivelong** [comment]
🤦

Okay now that's fixed. I love how I always screw up the update hook.

Preferable to be merged ahead of time to ensure users are able to install this plugin should PSUControl be updated before a repo refresh.  I have a locked issue on the repo mentioning that it requires a newer ver of PSUControl which hasn't been released yet.

**Review by jneilliii — APPROVED** [review]

**Pull request merged**
