### PR TITLE
Feature/revert pr 1132

### PR DESCRIPTION
**Pull request by bradcfisher**
Updates to revert the changes applied under #1132

### CODE REVIEW

**Comment by jneilliii** [comment]
@foosel I'm not sure of the implications of reverting here. do we need to bump the version higher on original repo than foirk and change the overlay back to  bradfischer?

**Comment by foosel** [comment]
If the version by the new maintainer points to their repo for updates, then yes.

**Comment by jneilliii** [comment]
@bradcfisher will need you to bump your version on the plugin to 1.3.2, please let me know once complete so I may complete this merge.

**Comment by jneilliii** [comment]
Sorry, I meant to say please bump your version to 0.3.2.

**Comment by bradcfisher** [comment]
@jneilliii Per your suggestion, I have released version 0.3.2.

**Review by jneilliii — APPROVED** [review]

**Pull request merged**
