### PR TITLE
Added ServoSpindle

### PR DESCRIPTION
**Pull request by synman**

### CODE REVIEW

**Comment by jneilliii** [comment]
With a quick look wouldn't [this ](https://github.com/synman/OctoPrint-Servospindle/blob/59bd4e51578c96b7a8b4897a010a3be813bb7168/octoprint_ServoSpindle/__init__.py#L144 ) match a lot of various commands, basically anything that specifies an S parameter? I see there's a space which may prevent the match, but was curious. Wouldn't it be better to potentially add a return early at the beginning of the gcode processing hook? That way you're not processing regex against every line in and out of the serial comm. Not really sure if this makes much of a difference processing wise or not.

```
if data[0:2] not in ["M3", "M5"]:
    return
```

**Comment by synman** [comment]
that is precisely the point as we are intercepting all spindle speed commands.  In the land of Grbl spindle speed can be standalone, or part of a modal (M)  or most Gcode (G) commands

```
M3 S1000
M5 S1000
S1000
G1 X123 Y123 S1000
```

are all valid

**Comment by synman** [comment]
you should see the regex matches I do inside of Better Grbl Supports gcode send and receive hooks lol

**Comment by synman** [comment]
I had benchmarked this stuff quite some time back so I had some code handy to do so here quickly as well:
```
from timeit import default_timer as timer
...
start = timer()
match = re.search(r".*[S]\ *(-?[\d.]+).*", data)
self._logger.debug("match string=[{}] result=[{}] time=[{}]".format(data, not match is None, timer() - start))
```
results in the follow for no match:
```
DEBUG - match string=[<IDLE|WPOS:-37.837,-18.050,27.823|FS:0,0|WCO:-302.163,-297.475,-28.823>] result=[False] time=[0.00020817600307054818]
DEBUG - match string=[OK] result=[False] time=[6.374999793479219e-05]
DEBUG - match string=[M105] result=[False] time=[4.854199505643919e-05]
DEBUG - match string=[<IDLE|WPOS:-37.837,-18.050,27.823|FS:0,0>] result=[False] time=[0.00013354099792195484]
DEBUG - match string=[OK] result=[False] time=[4.682299913838506e-05]
DEBUG - match string=[M105] result=[False] time=[7.41139956517145e-05]
DEBUG - match string=[<IDLE|WPOS:-37.837,-18.050,27.823|FS:0,0|OV:100,100,100>] result=[False] time=[0.00015916700067464262]
DEBUG - match string=[OK] result=[False] time=[5.0000002374872565e-05]
DEBUG - match string=[M105] result=[False] time=[3.4115000744350255e-05]
DEBUG - match string=[<IDLE|WPOS:-37.837,-18.050,27.823|FS:0,0>] result=[False] time=[9.359399700770155e-05]
DEBUG - match string=[OK] result=[False] time=[3.307300357846543e-05]
DEBUG - match string=[M105] result=[False] time=[4.671899660024792e-05]
DEBUG - match string=[<IDLE|WPOS:-37.837,-18.050,27.823|FS:0,0>] result=[False] time=[0.000141352997161448]
DEBUG - match string=[OK] result=[False] time=[4.562499816529453e-05]
DEBUG - match string=[M105] result=[False] time=[5.4114003432914615e-05]
DEBUG - match string=[<IDLE|WPOS:-37.837,-18.050,27.823|FS:0,0>] result=[False] time=[9.104100172407925e-05]
DEBUG - match string=[OK] result=[False] time=[3.333300264785066e-05]
```
for no match cases (the vast majority of the time as spindle speed changes typically only happen at the top of gcode files takes .2 ms (worse case).  

for match we're looking at:
```
DEBUG - match string=[M3 S1] result=[True] time=[6.849000055808574e-05]
DEBUG - match string=[M5 S0] result=[True] time=[4.5988999772816896e-05]
DEBUG - match string=[S1] result=[True] time=[3.8698002754244953e-05]
DEBUG - match string=[S40] result=[True] time=[5.5989003158174455e-05]
DEBUG - match string=[S0] result=[True] time=[5.411500023910776e-05]
```

of the sample worst result is .0684 ms

**Comment by synman** [comment]
should mention this time includes the overhead of instantiating the timer (twice) and all the work necessary to format a string with 3 parameters and log it.

**Comment by cp2004** [comment]
This one or #1004?

**Comment by cp2004** [comment]
As this PR is empty I'll assume #1004

**Comment by synman** [comment]
I dunno... I screwed up the first one

**Pull request closed without merging**
