### PR TITLE
OctoPrint-Slic3r supports python3

### PR DESCRIPTION
**Pull request by eyal0**

### CODE REVIEW

**Comment by eyal0** [comment]
Seems like python >2.7,<4 is the default anyway so I don't even know if it matters if this is merged.\

Is that true?

**Comment by cp2004** [comment]
No, default is still Py2, but there's a clever script that checks the compatibility string in your plugin's code, so if that changes then the plugin repository has done as well.

**Review by cp2004 — APPROVED** [review]

**Comment by eyal0** [comment]
> No, default is still Py2, but there's a clever script that checks the compatibility string in your plugin's code, so if that changes then the plugin repository has done as well.

That's pretty cool.  So the script that uploads this repo to the serve also visits each plugin and gets the compatibility info from the setup.py or whatever?  Neat.

**Comment by foosel** [comment]
Yep.. I also wrote a blog post about the automation on the plugin repo that takes care of stuff like that: 

https://octoprint.org/blog/2020/12/15/turning-a-static-website-more-dynamic/

**Pull request merged**
