### PR TITLE
Added plugin energeniecontrol

### PR DESCRIPTION
**Pull request by arlohb**

### CODE REVIEW

**Comment by jneilliii** [comment]
Link to product page seems broken? The line [here](https://github.com/arlohb/OctoPrint-EnergenieControl/blob/c3edd6ae2661d90c6b651bda8f53cfb483a940f3/octoprint_energeniecontrol/__init__.py#L164) in your plugin needs to be 
```
            energeniecontrol=dict(
```

**Comment by arlohb** [comment]
I've now fixed this. Is everything now correct?

**Comment by jneilliii** [comment]
Thanks, you don't have any other product page to link to? The one currently being used is broken and it appears this product may be discontinued.

**Comment by arlohb** [comment]
The link was working this morning, not sure why it no longer is. I've replaced it with working links.

**Review by jneilliii — APPROVED** [review]

**Pull request merged**
