### PR TITLE
Add ATXPiHat plugin

### PR DESCRIPTION
**Pull request by banichow**
Software support for the ATXPiHat expansion board.
Board Features include:
     ATX power on/off
     LED strip control
     EPO - emergency power off
     Cooling fan monitor
     12v/amp monitoring and control
     And a lot more.

### CODE REVIEW

**Comment by foosel** [comment]
Ah, there it is! :) Apologies for the complaints of the Travis build, something hiccuped hard in there unrelated to this PR... I'll take a proper look and merge this ASAP!

**Comment by kantlivelong** [comment]
@banichow you may want to fix the update check otherwise users will not be able to fetch the latest version.

**Comment by ieatacid** [comment]
> Apologies for the complaints of the Travis build, something hiccuped hard in there unrelated to this PR

@foosel:  When I added [TerminalCommands](https://github.com/ieatacid/OctoPrint-TerminalCommands) it failed with the current date (January something, 2018) and only passed when I changed the date to December 31st 2017. Not sure if that has anything to do with this.

**Comment by banichow** [comment]
@kantlivelong, I am new to this. After I got this loaded I was going to see how this works. Any help would be OUTSTANDING!......

**Comment by kantlivelong** [comment]
You can simply install the zip manually using the URL. Also note that you will need to create a release in GitHub.

**Comment by banichow** [comment]
Can you be more specific? Can you point me at an example? I see a lot related toward {version} added to the URL, but there is nothing that I can figure out (trust me I can be dumb often), on how to do it and test it.

**Comment by kantlivelong** [comment]
@banichow take a look at the [Software Update Plugin - github_release](http://docs.octoprint.org/en/master/bundledplugins/softwareupdate.html?highlight=github_release) docs.

**Comment by banichow** [comment]
Thank you Shawn for the link. I will have a looked at this already and am still confused. I will go back again and take a look when I get a minute. The yaml that is in the document is very specific to core items in OctoPrint. The update to the plugin is not specific regarding an example. Is there an example that I can look at? Maybe one of your plugins that works properly? If not, I will figure it out. I appreciate the help.
--BA

**Pull request closed without merging**
