### PR TITLE
Added plugin zupfe

### PR DESCRIPTION
**Pull request by glennerichall**

### CODE REVIEW

**Comment by jneilliii** [comment]
The body section above Setup should probably have more description of what zupfe is (include links to terms and privacy docs), identify that this plugin is connecting OctoPrint to an external server, and identify any subscription details for the service (if any).

**Comment by jneilliii** [comment]
Thanks for those changes, but please remove your gemfile.lock from the PR.

**Comment by jneilliii** [comment]
Sorry, I meant to say make sure it's not changed, not delete the file entirely.

**Comment by glennerichall** [comment]
Sorry for the sloppy commits, thank you for your time.

**Review by jneilliii — APPROVED** [review]

**Pull request merged**
