### PR TITLE
Add new filament sensor plugin.

### PR DESCRIPTION
**Pull request by Red-M**
The other two don't seem to work as the original plugin does not work and the newer one segfaults.
I've fixed this and added functionality from both into one along with my own additions.

### CODE REVIEW

**Comment by foosel** [comment]
You forgot to adjust the update information within your plugin code, its key is still `filamentsensor` but should be `filamentsensorng` :)

**Comment by Red-M** [comment]
I believe I've update that key and I've pushed a release for that as well.
Thanks for spotting that.

**Comment by Red-M** [comment]
Did I update the wrong thing?

**Comment by kantlivelong** [comment]
Hi @Red-M,

We don't get notifications for external projects. I've taken a look and it appears to be good now.

Thanks for your patience.

**Pull request merged**
