### PR TITLE
Continuous Print plugin

### PR DESCRIPTION
**Pull request by nukeem**
Continuous Print plugin

### CODE REVIEW

**Comment by nukeem** [comment]
The save on_after_startup just ensures that the enabled setting is set to false after startup. If its set to true then it can mess with future prints that may not be using the queue.
Sorry didn't realise the comparability was required. Ill add it in

**Comment by jneilliii** [comment]
@nukeem, I'm not sure if that boolean even needs to be a setting. Probably could get away with an internal assignment in `__init__`. I've seen weird things happen when saving at certain time, just can't remember if after startup was one of them. I will defer final review to @kantlivelong on this one and he can merge if he doesn't see any issues.

**Comment by nukeem** [comment]
@jneilliii  Thanks

**Comment by kantlivelong** [comment]
Yeah I don't get the point of saving `cp_enabled` if it's just going to essentially be initialized to `False` on startup. It seems to be being treated as a regular ol' bool in runtime. Not something I'd block this merge for though but you might want to re-eval it to see if it's really needed as-is.

@jneilliii Be sure to mark your approval on the review. :heavy_check_mark:

**Comment by jneilliii** [comment]
I thought I had @kantlivelong

**Comment by nukeem** [comment]
Thanks for the advice i will keep that in mind for the next release, i wasn't sure if using it as a variable would cause it to get garbage collected or something during run-time.

**Pull request merged**
