### PR TITLE
Update multicam.md

### PR DESCRIPTION
**Pull request by mikedmor**
Added octoprint version requirement of 1.9.1 for new webcam stack and BugFixes needed for the plugin to work as 1.9.0 breaks the plugin

_This pull request can be held off until 1.9.1 is released, but will be included in the plugin compatibility when released_

### CODE REVIEW

**Comment by foosel** [comment]
Careful with the wording here, 1.9.0 introduces webcam plugins. The new camera stack is something OS and OctoPi specific and not remotely connected to the 1.9.0 release.

**Comment by jneilliii** [comment]
Will wait for 1.9.1 release and then merge.

**Comment by mikedmor** [comment]
> Careful with the wording here, 1.9.0 introduces webcam plugins. The new camera stack is something OS and OctoPi specific and not remotely connected to the 1.9.0 release.

Apologies, definitely intended this to be related to the webcam plugin changes and not the Octopi Webcam Stack.

@jneilliii Thank you, this update should be ready for release when 1.9.1 is out. I will keep an eye out for when that happens, then push 0.4.0 to my repository with an octoprint requirement of 1.9.1 to install it.

**Comment by mikedmor** [comment]
Just a quick update, cp2004 from discords fix is now working on version 1.9.0, I updated to reflect that, you should be able to merge this now when ready as rc4 has been released which implements this patch. I am going to aim for a release by the end of this week, so no rush. thank you!

**Pull request merged**
