### PR TITLE
Added plugin webcamSB

### PR DESCRIPTION
**Pull request by quanticchaos**

### CODE REVIEW

**Comment by foosel** [comment]
Can you please add a description of what your plugin does to your listing? Currently it still says 

> **TODO**: Longer description of your plugin, configuration examples etc. This part will be visible on the page at http://plugins.octoprint.org/plugin/webcamSB/

**Comment by quanticchaos** [comment]
I'm very sorry. I Already made the changes and also changed the screenshots by some from the most recent version. It's an honour to meet you and thanks for everything.

**Comment by foosel** [comment]
Perfect, thank you! And: nice plugin :)

**Comment by quanticchaos** [comment]
Thanks a lot!

**Pull request merged**
