### PR TITLE
Add TPLinkSmartplug plugin

### PR DESCRIPTION
**Pull request by jneilliii**
Plugin that allows control of a TP-Link smartplug from the OctoPrint navbar.

### CODE REVIEW

**Comment by kantlivelong** [comment]
Looks like you made a change to **assets/img/plugins/YouTubeLive/settings_screenshot.jpg**. Could you correct it?

**Comment by jneilliii** [comment]
That's actually my plugin as well. If it's not too big of an issue I'd like to get that file added as well.

**Comment by foosel** [comment]
```
title: OctoPrint-TPLinkSmartplugin
description: Plugin to send M117 gcode messages to the web interface.
```

Copy paste error in the description? 🤔

**Comment by jneilliii** [comment]
Yes, sorry about that Gina.  I'll submit an updated pull request to adjust that.

**Comment by kantlivelong** [comment]
Merged #114.

Thanks

**Comment by GeekDad63** [comment]
General settings have disappeared after initial setup. Also can this be modified to power other wifi smart plugs. I.E. Tuya or wemo?

**Comment by jneilliii** [comment]
Please post issues for plugin over here. Include octoprint.log when posting if possible.

https://github.com/jneilliii/OctoPrint-TPLinkSmartplug/issues

**Pull request merged**
