### PR TITLE
Tobeca Plugin

### PR DESCRIPTION
**Pull request by tobeca**

### CODE REVIEW

**Comment by foosel** [comment]
@tobeca ping? :)

**Comment by tobeca** [comment]
Sorry, I don't see your message, i will modify my description...
And sorry for my english...

**Comment by foosel** [comment]
@tobeca no worries :)

**Comment by tobeca** [comment]
I hope this is good

**Comment by foosel** [comment]
:+1: I took the liberty to slightly adjust the short description because that's what gets displayed in OctoPrint's Plugin Manager and that was still a bit vague, see 983036d007eb194b7cb837c88fa009398c419923. I also changed the date to today since it took a couple of days to get that merged. Thanks! :)

**Comment by tobeca** [comment]
Thank you
Excuse me, i'm really newbi in GitHub, i don't create an archive for the plugin's installation, i thought that the source directory was enough

And so, i don't know how to create an "archive" directory in github, could you help me ?

**Comment by foosel** [comment]
Github does that automatically for you. Look on your repository page, there's a little button there that says "Clone or download":

image

If you click that, you get a dropdown:

image

And there's the archive link for your current `master` branch :) Looks like this: https://github.com/tobeca/OctoPrint-TobecaPlugin/archive/master.zip. Works for other branches too and even tags. It's always of the form `https://github.com/<username>/<repository>/archive/<branch or tag>.zip`. That's also how OctoPrint's own `octoprint dev plugin:new` command prefills the file to register here. Hope this helps!

I adjusted your listing to include that link, so that should now work out fine I hope.

**Comment by foosel** [comment]
Just saw that you manually added a tar.gz - you might want to remove that again now since it doesn't do anything but increase the size of the download. Cheers!

**Comment by tobeca** [comment]
Yes, i do actually
Thanks a lot

**Comment by tobeca** [comment]
It was so simply in fact. I just had to include the link !
Thanks again, Octoprint is very nice, and you are very helpfully...

**Pull request merged**
