### PR TITLE
New plugin: Added Complicated plugin

### PR DESCRIPTION
**Pull request by frenchie4111**

### CODE REVIEW

**Comment by frenchie4111** [comment]
It looks like the CI Failure is unrelated to the pull request

**Comment by foosel** [comment]
> It looks like the CI Failure is unrelated to the pull request

I agree.

I've taken a quick look at your plugin (btw, great idea! 👍) and noticed two things:

  * You have not implemented an [update hook](http://docs.octoprint.org/en/master/bundledplugins/softwareupdate.html#octoprint-plugin-softwareupdate-check-config) so users won't be able to update your plugin to newer versions from within OctoPrint but will have to do that manually. The plugin template should normally generate one for you as well.
  * You should [restrict access to the credentials (API key and so on) on the settings API](http://docs.octoprint.org/en/master/plugins/mixins.html#octoprint.plugin.SettingsPlugin.get_settings_restricted_paths) so that they will only be retrievable if a user is logged in as administrator.

You might want to look into this before this gets listed on the repository.

**Comment by frenchie4111** [comment]
Hey foosel. Thanks for the feedback, I will get those two changes implemented this week sometime.

**Comment by foosel** [comment]
@frenchie4111 Hey, just wondering what's the status here? :)

**Comment by frenchie4111** [comment]
Hey @foosel sorry, I updated the code a while ago, but never came back here to notify you. I think it should be good to go now

**Comment by foosel** [comment]
Perfect, date updated and merged then.

**Pull request merged**
