### PR TITLE
Added plugin smartfilamentsensor

### PR DESCRIPTION
**Pull request by maocypher**
The plugin enables that smart filament sensor that only detect movement and send toggling digital signals can be directly used with Octoprint when the sensor is connected to a Raspberry Pi.

### CODE REVIEW

**Review by jneilliii — CHANGES_REQUESTED** [review]
This PR needs work. your repo software update hook is pointing at the location from where you forked the plugin originally [here](https://github.com/maocypher/Octoprint-Smart-Filament-Sensor/blob/d50644dbb3bf32b13ddeb194ba1934ded5d332a9/octoprint_smart_filament_sensor/__init__.py#L149). That needs to be fixed. Out of personal curiosity, this plugin is designed to work with sensors like the BTT smart sensor right? I've been thinking of getting one of those, but didn't want to deal with breaking my printer case open and this plugin would resolve that for me.

**Comment by maocypher** [comment]
I updated the software hook to my archive [here](https://github.com/maocypher/Octoprint-Smart-Filament-Sensor/commit/be5df64a1acf677eba1a25406c59c00d4b5f992f).

> Out of personal curiosity, this plugin is designed to work with sensors like the BTT smart sensor right?
Yes, this is correct. I bought BTT Smart Filament Sensor with the knowledge, that I cannot directly add it to my printer mainboard (Stock Creality 1.1.5) and took the challange to make it available for Octoprint. Currently I am working on version 2.0 that is doing the detection based on the distance the filament put back, which I hope is more precise then based on simple timeout without a movement being detected.

**Review by jneilliii — APPROVED** [review]

**Comment by jneilliii** [comment]
Thanks @maocypher made some other small adjustments to your submission since this will only work on a pi, made os compatibility linux only....

**Comment by maocypher** [comment]
Thank you 👍

**Comment by mpd352** [comment]
This plugin is not compatible with Python 3.  Gets this error message: 2020-10-18 19:08:44,997 - octoprint.plugin.core - WARNING - Plugin Smart Filament Sensor (1.0.0) is not compatible to Python 3.7.3 (compatibility string: >=2.7,<3).

I love the idea of this feature and want to use it.  Any idea when it will be compatible with P3.  That's kina critical as Octoprint is pushing us all hard to update to P3.

**Comment by jneilliii** [comment]
You might want to raise that question on the plugin's repository.

**Comment by mpd352** [comment]
The repository page says to report it here.  Filament Sensor Reloaded is P3 compatible, and is up and running.  Thanks.

**Comment by jneilliii** [comment]
I see now that @maocypher has not enabled an issue tracker on his repository. The plugin submission here to the repo indicates it was python 3 compatible. @maocypher you need to add the line `__plugin_pythoncompat__ = ">=2.7,<4"` toward the end of your init.py file just below the `__plugin_version__ ` line.

**Comment by jneilliii** [comment]
@mpd352 you can try this version...copy/paste the URL below into Plugin Manager> Get More > ...from URL and click install.

```
https://github.com/jneilliii/Octoprint-Smart-Filament-Sensor/archive/master.zip
```

**Comment by maocypher** [comment]
Sorry for the inconvinence, I am new to working with GitHub.
Issue tracker is now enabled https://github.com/maocypher/Octoprint-Smart-Filament-Sensor/issues
I will take care about this today!

**Pull request merged**
