### PR TITLE
Add Z probe offset control plugin

### PR DESCRIPTION
**Pull request by razerraz**

### CODE REVIEW

**Comment by razerraz** [comment]
This is the first step of splitting ABL Expert plugin in multiple ones. It add z probe offset control as it seems the first reason of installing ABL Export for a majority of users, and I want to have smaller projects easiest to maintain.
Unfortunately it doesn't want to merge and I don't have a clue why

**Comment by razerraz** [comment]
Done

**Comment by jneilliii** [comment]
@razerraz you completely removed the detail description of your plugin at the bottom of template after the last ----. This will result in a blank page. You should put that back in. Also, featured image in the template is not included on the page sho you may want tp add it in that detailed description as well.

**Comment by jneilliii** [comment]
@foosel I'll have to defer to you on this review as the plugin checks are outside of github and I'm not familiar with that. Also appears like there might be some coding files included in the repo that shouldn't be (ie src folder).

**Comment by razerraz** [comment]
That src folder is not installed anywhere during setup process, as the manifest attests.

I use transcoders to convert pug files into html jinja templates, same with ES6 class based converted into ES4 using babel js. "Src" contains sources files, that are lot more readable and easiest to work with. I believe they have to be in the repo for eventual contibutors.

And by the way, ABL Expert shares exactly the same behavior, I've just removed bugs in the version checker

**Comment by jneilliii** [comment]
I installed this and for some reason it doesn't appear to show up anywhere except in plugin manager.

**Comment by razerraz** [comment]
Hope we get rid soon of this stoneage python2:

`Python 2.7.18 (default, Apr 23 2020, 22:32:06) 
[GCC 9.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ast
>>> with open('__init__.py', 'rb') as f:
...     ast.parse(f.read())
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 100
    subcode=None, tags=None, **kwargs):
          ^
SyntaxError: invalid syntax
`

`Python 3.8.3 (default, May 17 2020, 18:15:42) 
[GCC 10.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ast
>>> with open('__init__.py', 'rb') as f:
...     ast.parse(f.read())
... 
<_ast.Module object at 0x7fca4b3b08b0>
`


I recon not having tested on it, sorry about it. Is python2 always the default for new octoprint installs ?
Will fix it tomorow anyway

Thanks though

**Comment by jneilliii** [comment]
Lol, that is what is still currently shipped with octopi. If you change your compatibility flags to python 3 only then that's a non issue, but your visibility will be only to us rare few that have manually installed/upgraded.

**Comment by jneilliii** [comment]
Thanks @foosel. @razerraz once you've either made it Python2 compatible or update the compatibility flags to Python 3 only this PR can be merged, your choice.

**Comment by razerraz** [comment]
@jneilliii   I've just released 0.2 that should be python compatible. If you have a couple of minutes to test before merging I'll be grateful

**Comment by jneilliii** [comment]
works like a charm, thanks @razerraz. I'll do some final checks and then merge.

**Comment by razerraz** [comment]
Thanks to you.

**Pull request merged**
