### PR TITLE
Added plugin USB Relay Control

### PR DESCRIPTION
**Pull request by abudden**

### CODE REVIEW

**Comment by abudden** [comment]
> Preview URL (manually generated) https://cp2004-plugins-octoprint-org-git-pr1014-cp2004.vercel.app/

Thanks for producing that.  Is there anything else you need from me for this submission?

**Comment by cp2004** [comment]
> > Preview URL (manually generated) https://cp2004-plugins-octoprint-org-git-pr1014-cp2004.vercel.app/
> 
> Thanks for producing that. Is there anything else you need from me for this submission?

Not that I can see at the moment - the plugin will be reviewed, but this process can take some time as the plugin reviewers all have full time jobs. If we need anything else or changes are needed, they'll be in touch on this PR.

**Comment by abudden** [comment]
> > > Preview URL (manually generated) https://cp2004-plugins-octoprint-org-git-pr1014-cp2004.vercel.app/
> > 
> > 
> > Thanks for producing that. Is there anything else you need from me for this submission?
> 
> Not that I can see at the moment - the plugin will be reviewed, but this process can take some time as the plugin reviewers all have full time jobs. If we need anything else or changes are needed, they'll be in touch on this PR.

Thanks for the quick reply.  No rush for reviewing it; I just wanted to check I hadn't missed anything important.

**Review by cp2004 — CHANGES_REQUESTED** [review]
My points for a plugin review:

**Documentation**

* The [setup instructions](https://github.com/abudden/OctoPrint-USBRelayControl#setup) mention installing extra dependencies to use the plugin. But both these commands:
  ```
  python3 -m pip install --upgrade setuptools
  python3 -m pip install hidapi
  ```
  Will not make a difference to the operation of this plugin in OctoPrint, which runs in it's own virtual environment. Since you've listed the `hidapi` package as a dependency, this can just be removed. I'm not sure about the `libusb-1.0-0-dev libudev-dev` packages being installed on most systems.

**Code**

* Returning a flask response from the `on_settings_save` function will not work, the expected return from this function (if any) is a diff of what settings were saved, nothing will happen if a flask response is returned. [Documentation link](https://docs.octoprint.org/en/master/plugins/mixins.html#octoprint.plugin.SettingsPlugin.on_settings_save). In code [here](https://github.com/abudden/OctoPrint-USBRelayControl/blob/ed4670483501bbfd7ecb57c26a1174748060413a/octoprint_usbrelaycontrol/__init__.py#L58) and [here](https://github.com/abudden/OctoPrint-USBRelayControl/blob/ed4670483501bbfd7ecb57c26a1174748060413a/octoprint_usbrelaycontrol/__init__.py#L62)
* In `on_after_startup` you try and run the same code as the settings - there is no flask context available here since it's not a web request handler.
* The `user_permission` has been deprecated since 1.4.0, new plugins should use the new permissions system in `octoprint.access` instead. [Here in your plugin](https://github.com/abudden/OctoPrint-USBRelayControl/blob/ed4670483501bbfd7ecb57c26a1174748060413a/octoprint_usbrelaycontrol/__init__.py#L127)

**Other**
* The release numbers in your plugin's setup.py file and the tag on GitHub don't match. In setup.py it is `1.0.0`, the GitHub release it is `0.1.0`.


I think that's all I have for a review of this plugin - the rest of it looks OK. Let me know when you've addressed the points above and I think we can list this plugin.

**Comment by abudden** [comment]
Hi @cp2004 

All the comments look reasonable and fair, thanks.  I'm going through and trying to address them, but I've got a little confused with the permissions thing (I copied the original from an existing plugin so I didn't really know what a lot of the code was doing as you can probably tell).

Based on the PSUControl plugin, I think I need to include something that looks like this:

```python
from octoprint.access.permissions import Permissions
# ...

if not Permissions.PLUGIN_USBRELAYCONTROL_CONTROL.can():¦
    return flask.make_response("Insufficient rights", 403)¦
```

However, I can't see where the PLUGIN_USBRELAYCONTROL_CONTROL thing is defined.  I based it on the PSU Control version, which has "Permissions.PLUGIN_PSUCONTROL_CONTROL.can()", but I've searched for that "PLUGIN_PSUCONTROL_CONTROL" thing and can only find it inside the PSU Control plugin.

Am I missing something obvious?

Thanks,

Al

**Comment by cp2004** [comment]
I should write a guide in the plugins section of the docs covering adding permissions to a plugin, I think all the docs are there but just not in one clear place, they are scattered.

You have to define the set of permissions first, in PSU control it is here https://github.com/kantlivelong/OctoPrint-PSUControl/blob/c0490c8c30388a649cc6e87525241dfe3b5923ca/octoprint_psucontrol/__init__.py#L846-L854 with the `octoprint.access.permissions` hook.

**Comment by abudden** [comment]
> I should write a guide in the plugins section of the docs covering adding permissions to a plugin, I think all the docs are there but just not in one clear place, they are scattered.
> 
> You have to define the set of permissions first, in PSU control it is here https://github.com/kantlivelong/OctoPrint-PSUControl/blob/c0490c8c30388a649cc6e87525241dfe3b5923ca/octoprint_psucontrol/__init__.py#L846-L854 with the `octoprint.access.permissions` hook.

Thanks for that.  I thought that made sense, but it's not working so I'm obviously doing something wrong.  Where does the `_PSUCONTROL_` bit of the definition come from?  

In [the latest commit](https://github.com/abudden/OctoPrint-USBRelayControl/commit/3707f2956cf046a8cde3fcfb8e8e7f9d9b2960cd#diff-67d4a08d9f8cd2b0a20a48f79579a60cbb3662ed852bedd61bfafc058035b293R131), I tried to fix this (along with the other review comments).  I lifted the code from PSU Control and copied it as closely as I could (with changes from PSU Control to USB Relay Control, obviously. but the logs now show:

```
2022-02-28 18:06:03,238 - octoprint.server.api - ERROR - Error while executing SimpleApiPlugin usbrelaycontrol
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/server/api/__init__.py", line 158, in pluginCommand
    response = api_plugin.on_api_command(command, data)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1737, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_usbrelaycontrol/__init__.py", line 131, in on_api_command
    if not Permissions.PLUGIN_USBRELAYCONTROL_CONTROL.can():
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/vendor/flask_principal.py", line 347, in can
    return self.require().can()
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/access/permissions.py", line 175, in can
    raise UnknownPermission(self.key)
octoprint.access.permissions.UnknownPermission: Unknown permission: PLUGIN_USBRELAYCONTROL_CONTROL
```

**Comment by abudden** [comment]
> You need to register the `octoprint.access.permissions` hook, to collect the permissions. In the bottom of the plugin, there is a `__plugin_hooks__` definition, which links that function to the permissions collector. OctoPrint will then create the permissions, based on this kind of template `PLUIN_{plugin id}_{name}`
> 
> This is the documentation: https://docs.octoprint.org/en/master/plugins/hooks.html#octoprint-access-permissions

Thanks - that's sorted it out.

I **think** I've addressed all your comments now; please let me know if I've missed anything.

**Review by cp2004 — APPROVED** [review]

**Pull request merged**
