### PR TITLE
OctoPrint-M300Player

### PR DESCRIPTION
**Pull request by jneilliii**
Plugin that will play M300 beeps in the web interface.

### CODE REVIEW

**Comment by OllisGit** [comment]
Hi @jneilliii ,

I was trying to install the plugin, but received the following error. I ave no idea why.
System: Mac OS Mojave
OctoPrint 1.4.0
python:
|      pip: 20.0.2
|      version: 2.7.9

```
Installing plugin from https://github.com/jneilliii/OctoPrint-M300Player/archive/master.zip...
/Users/o0632/0_Projekte/3DDruck/OctoPrint/octoprint_latest/venv-2/bin/python -m pip --disable-pip-version-check install https://github.com/jneilliii/OctoPrint-M300Player/archive/master.zip --no-cache-dir
Collecting https://github.com/jneilliii/OctoPrint-M300Player/archive/master.zip
Downloading https://github.com/jneilliii/OctoPrint-M300Player/archive/master.zip
ERROR: Command errored out with exit status 1:
command: /Users/o0632/0_Projekte/3DDruck/OctoPrint/octoprint_latest/venv-2/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/yr/m1wj20qn5lqfhnz403tqqrch0000gn/T/pip-req-build-o2aBDM/setup.py'"'"'; __file__='"'"'/private/var/folders/yr/m1wj20qn5lqfhnz403tqqrch0000gn/T/pip-req-build-o2aBDM/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/yr/m1wj20qn5lqfhnz403tqqrch0000gn/T/pip-req-build-o2aBDM/pip-egg-info
cwd: /private/var/folders/yr/m1wj20qn5lqfhnz403tqqrch0000gn/T/pip-req-build-o2aBDM/
Complete output (2 lines):
Found packages: set(['octoprint_M300 Player'])
error in OctoPrint-M300Player setup command: ("EntryPoint must be in 'name=module:attrs [extras]' format", 'M300 Player = octoprint_M300 Player')
----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Error!
Could not parse output from pip, see plugin_pluginmanager_console.log for generated output
```

**Comment by foosel** [comment]
Looks like the identifier in setup.py is invalid (there's a space in there) and that in turn causes the package name to become invalid. Removing the space should fix it.

**Comment by jneilliii** [comment]
🤦‍♂️ sorry guys, late night copy\paste mistake, that was supposed to go in name...fixed now.

**Comment by OllisGit** [comment]
I thought you never sleep and make no errors...24h a day, 7d a week writing plugin/support the community...do you have a 9-5 job?
Wow, awesome!!

It worked.....but ```Sweet_Child_o_Mine.gcode``` doesn't sound like a Guns n Roses-Song ;-)

**Comment by jneilliii** [comment]
Lol, If you tweak thr settings some you cam gett it to sound more like the real song...

**Pull request merged**
