### PR TITLE
Added plugin ABL_Expert

### PR DESCRIPTION
**Pull request by razerraz**

### CODE REVIEW

**Comment by kantlivelong** [comment]
Hi @razerraz,

Thanks for your submission. I've taken a look at this PR as well as the plugin itself and have one concern.

The plugin source is being hosted on framagit.org which is fine but looking at the plugin source I that [the update check is specifying github_release](https://framagit.org/razer/Octoprint_ABL_Expert/blob/master/octoprint_ABL_Expert/__init__.py#L37). I'm fairly certain that the version update check will fail. Perhaps you can make use of an alternative update check method? See [Software Update Plugin:Version checks](http://docs.octoprint.org/en/master/bundledplugins/softwareupdate.html#version-checks)

**Comment by razerraz** [comment]
Dawn, I miss that
Will take a look soon
Thanks

**Comment by razerraz** [comment]
Does it seems ok to you right now ?

https://framagit.org/razer/Octoprint_ABL_Expert/commit/43b5ec462dc1722880494bdbae9df550591af220

**Comment by razerraz** [comment]
Yes by tweaking octoprint plugin repo url, pointing my fork
Looks fine...

**Comment by kantlivelong** [comment]
Merged :+1:

**Pull request merged**
