### PR TITLE
Added plugin nexmonotifier

### PR DESCRIPTION
**Pull request by gfk76**

### CODE REVIEW

**Comment by kantlivelong** [comment]
Hi @gfk76,

Thanks for the submission. I took a look at this PR and the source for the plugin and only noticed one thing.

- You are importing the `nexmo` module but do not have it defined as a dependency in [requirements.txt](https://github.com/gfk76/OctoPrint-Nexmonotifier/blob/master/requirements.txt)

**Comment by gfk76** [comment]
> Hi @gfk76,
> 
> Thanks for the submission. I took a look at this PR and the source for the plugin and only noticed one thing.
> 
> * You are importing the `nexmo` module but do not have it defined as a dependency in [requirements.txt](https://github.com/gfk76/OctoPrint-Nexmonotifier/blob/master/requirements.txt)

Prerequisites added to requirements.txt :-)

**Comment by kantlivelong** [comment]
Hey sorry one last thing. You need to make a release on GitHub.

**Comment by gfk76** [comment]
> Hey sorry one last thing. You need to make a release on GitHub.

Done. :-)

**Comment by kantlivelong** [comment]
Thanks :+1: 

Merged

**Pull request merged**
