### PR TITLE
Adopt Filament Sensor Reloaded

### PR DESCRIPTION
**Pull request by ssorgatem**
The plugin was abandoned ( https://github.com/OctoPrint/plugins.octoprint.org/issues/499 ) , and I've ported it to Python3 and incorporated some fixes and features that were floating around.

### CODE REVIEW

**Review by jneilliii — APPROVED** [review]

**Comment by jneilliii** [comment]
Thank you for such a complete adoption PR @ssorgatem, made it very easy to approve/merge.

**Comment by ssorgatem** [comment]
@jneilliii sorry to bother you again, but I cannot see the plugin at all from the plugin manager in my instance.
Is that normal or did I mess up somewhere?

**Comment by foosel** [comment]
date: 2020-09-27 018:00:00Z

Just a hunch but that's an invalid timestamp. Gonna fix that.

**Comment by ssorgatem** [comment]
Mmm, turns out I still see the old, python3-incompatible version.
But i cannot see the new marlingcodedocumentation plugin either, so maybe it's a problem on my end?

**Comment by ssorgatem** [comment]
Nevermind, it was just me being dumb.
I just discovered the "refresh list from server" option 😅
Everything works.

**Comment by foosel** [comment]
Aaah, yeah. I thought you'd already done that 😅 Cache period is 6h I think, unless manually refreshed.

**Comment by jneilliii** [comment]
> date: 2020-09-27 018:00:00Z

sorry for missing that Gina, my old eyes I guess.

**Pull request merged**
