### PR TITLE
added plugin "Filament Sensor"

### PR DESCRIPTION
**Pull request by MoonshineSG**
new plugin for Filament Sensor

### CODE REVIEW

**Comment by MoonshineSG** [comment]
whoops... my second plugin got merged into this... bad github skills...

**Comment by foosel** [comment]
Ah well, one less click for me I guess ;)

**Comment by MoonshineSG** [comment]
is there any way to make the link to thingiverse a link not just plain text ?

**Comment by foosel** [comment]
Yeah, regular markdown. [Just adjusted it](https://github.com/OctoPrint/plugins.octoprint.org/commit/8f14d0269f5821f5a8cd6c73cf45fec65551f79e).

**Pull request merged**
