### PR TITLE
add heatbedsavety, hopefully no requirements left

### PR DESCRIPTION
**Pull request by linux-paul**

### CODE REVIEW

**Comment by linux-paul** [comment]
Hi, after testing on local jekyll and passing this stages here, I got a mail for github with unknown TAG error which oints to line 16 of /_layouts/default.html`?. 
I'm pretty new to this stuff and I didn't get the issue

**Comment by Salamafet** [comment]
> Hi, after testing on local jekyll and passing this stages here, I got a mail for github with unknown TAG error which oints to line 16 of /_layouts/default.html`?.
> I'm pretty new to this stuff and I didn't get the issue

Same email on my commit
https://github.com/OctoPrint/plugins.octoprint.org/pull/581

I don't understand where is the problem

**Comment by jneilliii** [comment]
Yeah, you can ignore those emails on your side guys. It's part of the github actions. As long as the checks pass here on your PR, it's ready for review.

**Comment by jneilliii** [comment]
You're also missing your update hook [here](https://github.com/linux-paul/OctoPrint-Heatbedsavety/blob/763334b32081b315bfa8bee889949a80aeff89e9/octoprint_heatbedsavety/__init__.py#L136-L138) in this section. This means once the plugin is installed it will never get updates if you make changes. Needs to be something like this.

```
	__plugin_hooks__ = {
		"octoprint.comm.protocol.temperatures.received": __plugin_implementation__.readtemperature,
		"octoprint.plugin.softwareupdate.check_config": __plugin_implementation__.get_update_information
	}
```

**Comment by linux-paul** [comment]
fixed :)

**Pull request merged**
