### PR TITLE
Added plugin GcodeEditor

### PR DESCRIPTION
**Pull request by ieatacid**

### CODE REVIEW

**Comment by ieatacid** [comment]
Did I get it right? >.<

**Comment by kantlivelong** [comment]
PR looks good and this plugin seems useful. The only concern I have is that it seems to load the entire file in memory on the browser which can be a performance problem.

I'll leave this up to Gina to merge.

**Comment by ieatacid** [comment]
> The only concern I have is that it seems to load the entire file in memory on the browser
What other way to do it? Stream only the 30 or so lines being displayed at a time? I don't know how to do that, nor have the time to learn :\  Wouldn't OctoPrint still have to load the entire file?

**Comment by ieatacid** [comment]
Or maybe determine that limit based on system RAM. I haven't had any problems so far, though. It just takes longer to load a larger file.

**Comment by ieatacid** [comment]
I actually came across that issue when I was searching for a gcode editor plugin :)

Thanks for the suggestions and explanations. I'll have more time to work on it this weekend.

**Pull request merged**
