### PR TITLE
Added plugin progress_title

### PR DESCRIPTION
**Pull request by pwnbus**

### CODE REVIEW

**Comment by foosel** [comment]
Hi there, nice plugin! There's one open point however:

  * Your plugin is not Python 3 compatible. Python 2 is EOL. OctoPrint 1.4.0 does support Python 2 and Python 3, plugins will be expected to do so as well (or at least support Python 3) during a transition period of roughly a year after the release of OctoPrint 1.4.0 to allow a migration of the whole ecosystem. Newly registered plugins should be Python 3 compatible out of the box. [See this forum thread for more information](https://community.octoprint.org/t/towards-python-3-and-octoprint-1-4-0/12382?u=foosel).

Can you take a look at that and ping me once that's taken care of? Thank you!

**Comment by pwnbus** [comment]
@foosel Thank you for your kind words! I've updated my plugin to support python3, and tested to verify everything should be all set.

Please let me know if there's anything else that's required!

**Comment by foosel** [comment]
All good now, thanks! 👍

**Comment by xia0** [comment]
nice plugin!

**Pull request merged**
