### PR TITLE
Added SMuFF plugin V1.1.4 to repository

### PR DESCRIPTION
**Pull request by technik-gegg**

### CODE REVIEW

**Comment by jneilliii** [comment]
@technik-gegg nice plugin. I've merged, but would recommend updating the names to be consistent between the plugin's name in setup.py to the override in init.py and the update check callback. Not really an issue.

**Comment by jneilliii** [comment]
@technik-gegg just noticed when the page built that your second screenshot didn't show up. File names including extensions are case sensitive. Please correct that.

**Comment by technik-gegg** [comment]
@jneilliii 
Thanks for the hint. Did correct both.

**Comment by jneilliii** [comment]
@technik-gegg you'll need to submit a new PR for the case change here.

**Comment by technik-gegg** [comment]
Silly me. It was the wrong pic anyways. Now it's the right one.

**Comment by jneilliii** [comment]
thanks

**Pull request merged**
