### PR TITLE
new plugin : shutdown printer

### PR DESCRIPTION
**Pull request by devildant**
I create this plugin to send the code M81 to turn off the printer after the print job is done.
it works in partnership with the OctoPrint-TPLinkSmartplug plugin.

### CODE REVIEW

**Comment by foosel** [comment]
Just took a quick look. Your update configuration [here](https://github.com/devildant/OctoPrint-ShutdownPrinter/blob/9df752a1bbb5a969ea8a4a4cb7aa9c9e539942f4/octoprint_shutdownprinter/__init__.py#L201-L215) is broken, it's pointing at a non existing repository `OctoPrint/OctoPrint-ShutdownPrinter`.

You rather want it to look like this:

``` python
                return dict(
                        shutdownprinter=dict(
                        displayName="Shutdown Printer",
                        displayVersion=self._plugin_version,

                        # version check: github repository
                        type="github_release",
                        user="devildant",
                        repo="OctoPrint-ShutdownPrinter",
                        current=self._plugin_version,

                        # update method: pip w/ dependency links
                        pip="https://github.com/devildant/OctoPrint-ShutdownPrinter/archive/{target_version}.zip"
                )
        )
```

Otherwise people won't be able to get notified of updates of your plugin or update from within OctoPrint.

You might want to fix this before I merge this PR :)

**Comment by devildant** [comment]
hello, sorry for the mistake, I corrected the problem :)

**Comment by foosel** [comment]
Not completely ;) `user` still has the wrong value. Should also say `devildant` instead `OctoPrint`. One bit is telling where to look for release information (here: a github user and repo). The other bit is telling OctoPrint how to install updates (here: via pip from the specified github archive URL). Both need to point at the right location for things to work.

**Comment by devildant** [comment]
oh yes, my bad again, I hope that this time is good :p

**Comment by foosel** [comment]
Yep! 👍

**Pull request merged**
