### PR TITLE
add OctoDash Companion

### PR DESCRIPTION
**Pull request by jneilliii**
👋

### CODE REVIEW

**Comment by foosel** [comment]
Featured image is missing ;)

**Comment by jneilliii** [comment]
dang it

**Comment by jneilliii** [comment]
> Featured image is missing ;)

It is there, I just don't have any other screenshots. I think that is a CI issue?

**Comment by foosel** [comment]
No, the data format requires to have a set of screenshots and to allow marking one of those as featured. The CI is detecting that you have defined one featured but the screenshot list is missing.

Though, I gotta say, it might make sense to just autofix stuff like that.

**Comment by jneilliii** [comment]
screenshot list added

**Pull request merged**
