### PR TITLE
Update OctoAutoremote.md

### PR DESCRIPTION
**Pull request by trunzoc**
Apparently, I missed the actual file in the "archive" setting.  I fixed it.

### CODE REVIEW

**Comment by kantlivelong** [comment]
Danke Schön!

**Comment by trunzoc** [comment]
Thank for the quick response!

**Comment by trunzoc** [comment]
Sorry to be such a nuisance.  Even though the plugin repository shows the proper archive now, the plugin installer still seems to only be seeing the link to my repository, not the master.zip.

Is there anything else I need to do to fix it?

**Comment by kantlivelong** [comment]
You need to refresh the data from the repo. When at the installation window
click the wrench then refresh.

-Shawn

**Pull request merged**
