### PR TITLE
New Plugin: OctoPrint-hueCommands 

### PR DESCRIPTION
**Pull request by LMS0815**

### CODE REVIEW

**Comment by LMS0815** [comment]
THX

**Comment by foosel** [comment]
Hi there! I took a quick look at your plugin and there are a couple of open points to address before it can be registered: 

  * https://github.com/LMS0815/OctoPrint-hueCommands/blob/master/octoprint_huecommands/__init__.py#L146 -> have you tested printing with this line? I'm pretty sure that will prevent any commands at all from being sent to the printer and should be one tab further to the right instead (to prevent the HUE commands from being sent, which would make sense). Either that or the indentation is playing tricks on me here.
  * https://github.com/LMS0815/OctoPrint-hueCommands/blob/master/octoprint_huecommands/__init__.py#L211 -> your update check points to the wrong archive URL 
  * You should [restrict access to the credentials (API key and so on) on the settings API](http://docs.octoprint.org/en/master/plugins/mixins.html#octoprint.plugin.SettingsPlugin.get_settings_restricted_paths) so that they will only be retrievable if a user is logged in as administrator.
  * You marked the listing Py3 compatible, but forgot the relevant line in the plugin itself. [See this forum thread for more information](https://community.octoprint.org/t/towards-python-3-and-octoprint-1-4-0/12382?u=foosel).

Can you give me a ping once that's taken care of so I can take another look? Thanks!

**Comment by LMS0815** [comment]
Updates entered. Please proceed.

12. Februar 2020 16:28, "Gina Häußge" <notifications@github.com (mailto:notifications@github.com?to=%22Gina%20H%C3%A4u%C3%9Fge%22%20<notifications@github.com>)> schrieb:
	Hi there! I took a quick look at your plugin and there are a couple of open points to address before it can be registered: 
	*  https://github.com/LMS0815/OctoPrint-hueCommands/blob/master/octoprint_huecommands/__init__.py#L146 (https://github.com/LMS0815/OctoPrint-hueCommands/blob/master/octoprint_huecommands/__init__.py#L146) -> have you tested printing with this line? I'm pretty sure that will prevent any commands at all from being sent to the printer and should be one tab further to the right instead (to prevent the HUE commands from being sent, which would make sense). Either that or the indentation is playing tricks on me here. 
	*  https://github.com/LMS0815/OctoPrint-hueCommands/blob/master/octoprint_huecommands/__init__.py#L211 (https://github.com/LMS0815/OctoPrint-hueCommands/blob/master/octoprint_huecommands/__init__.py#L211) -> your update check points to the wrong archive URL 
	* You should restrict access to the credentials (API key and so on) on the settings API (http://docs.octoprint.org/en/master/plugins/mixins.html#octoprint.plugin.SettingsPlugin.get_settings_restricted_paths) so that they will only be retrievable if a user is logged in as administrator. 
	* You marked the listing Py3 compatible, but forgot the relevant line in the plugin itself. See this forum thread for more information (https://community.octoprint.org/t/towards-python-3-and-octoprint-1-4-0/12382?u=foosel). 
	Can you give me a ping once that's taken care of so I can take another look? Thanks!

**Comment by LMS0815** [comment]
Added some code improvements.

**Comment by foosel** [comment]
Just a quick ping to let you know, I haven't forgotten you, just have my hands full with the 1.4.0 RCs. But I'll get back to this ASAP (hopefully this week!)

**Comment by LMS0815** [comment]
No problem I have taken the time to improve the code.

**Comment by LMS0815** [comment]
Just a small reminder. Please review or reject my pull request.

**Comment by foosel** [comment]
1.4.0 took a bit of a toll, sorry for the ongoing delay.

**Pull request merged**
