### PR TITLE
Added plugin ws281x_led_status

### PR DESCRIPTION
**Pull request by cp2004**
:tada: My first (official) plugin.

Hopefully I did it right, adding [WS281x LED Status](https://github.com/cp2004/OctoPrint-WS281x_LED_Status)!

Just about to create a release as well so it's fully polished.

On to the next one!

### CODE REVIEW

**Comment by cp2004** [comment]
Hope the failure is not my fault...? Could be because my fork of the repo is a bit old, so it thinks I have changed lots of things?

**Comment by jneilliii** [comment]
@cp2004 the failure appears to be on someone else's file, unrelated to your submission. There is one problem with your plugin however. Your update check dictionary needs to match your plugin_identifier. Change `rgb_led_status` to `ws281x_led_status` [here](https://github.com/cp2004/OctoPrint-WS281x_LED_Status/blob/8ad11f6c25ad656625949fd78dca87511f02094c/octoprint_ws281x_led_status/__init__.py#L465)

**Comment by foosel** [comment]
@cp2004 if you rebase your PR against the current `gh-pages` branch, the problem should vanish.

Might have to look into somehow doing that automatically during validation or something to avoid scenarios like this one...

**Comment by cp2004** [comment]
@jneilliii - Fixed the update dictionary, forgot to change that bit I guess 🤷 Still worked, so didn't spot in my test

@foosel - Rebase done, check passed

**Comment by jneilliii** [comment]
@cp2004 you're doing too much at once right now...change was not put into master. You need to double-check this whole section...

https://github.com/cp2004/OctoPrint-WS281x_LED_Status/blob/master/octoprint_ws281x_led_status/__init__.py#L465-L478

**Comment by cp2004** [comment]
I have 2 screens, just about managing (not really). Had committed, but forgotten to push, _sighs_. I've got a new release drafted to get it up to speed if that's the only issue.

**Pull request merged**
