### PR TITLE
Added plugin Detector2.

### PR DESCRIPTION
**Pull request by mikulash**
AI detection on frontend

### CODE REVIEW

**Comment by jneilliii** [comment]
I think the email password should not be stored in plain text if it's avoidable. The [Wyze](https://github.com/OctoPrint/plugins.octoprint.org/pull/1030#issuecomment-1070305168) plugin recently implemented this in their plugin and might be a good reference point on how to do it.

**Comment by mikulash** [comment]
thanks for the quick response! I added the suggested encryption

**Review by jneilliii — APPROVED** [review]

**Comment by jneilliii** [comment]
You need to crate a release on your GitHub repository that matches the current version 0.1.0 in setup.py. When new versions are ready update setup.py and create a new release with a matching version tag that way users that have the plugin installed will get update notices.

**Comment by mikulash** [comment]
oh, did not know about this. it is done. thank you for reviewing this even on weekend

**Comment by cp2004** [comment]
Is there any noticeable performance impact or benefit sending the images over the websocket vs. serving a HTTP request?

Other question, there is a get request for the snapshot image, but the response never seems to be used: https://github.com/mikulash/Octoprint-detector2/blob/bb561255255ae524f6e1267978159076fe4765bd/octoprint_detector2/__init__.py#L66
Is this needed for something I haven't spotted, or can it be removed?

**Comment by jneilliii** [comment]
> Is this needed for something I haven't spotted, or can it be removed?

Good point, it doesn't appear to be necessary and would improve performance.

**Comment by mikulash** [comment]
oh, did not notice that, thanks, i have removed it

**Pull request merged**
