### PR TITLE
Added plugin: OctoRemote

### PR DESCRIPTION
**Pull request by pkElectronics**

### CODE REVIEW

**Comment by foosel** [comment]
Sweet! Got a video of it in action? :)

**Comment by pkElectronics** [comment]
Of course

https://www.instagram.com/p/BSHOSGsj5X2/

**Comment by foosel** [comment]
Now all that's left is printing custom keypads :D

**Comment by pkElectronics** [comment]
Well, that´s exactly what I am working on at the moment.

2017-03-30 11:18 GMT+02:00 Gina Häußge <notifications@github.com>:

**Pull request merged**
