### PR TITLE
Plugin completely rewritten. Now v0.3.0. Tested against OctoPrint 1.7.3 & 1.8.0rc3

### PR DESCRIPTION
**Pull request by gruvin**

### CODE REVIEW

**Comment by cp2004** [comment]
You are listed as an author of the original plugin since it was already adopted, there's no need to register a new plugin just update the old listing please.

**Comment by gruvin** [comment]
I am not an author of the original plugin. :/

**Comment by gruvin** [comment]
Or rather -- I am confused. Far as I know, I did not create a new plugin. I
merely updated the existing webcamtab_g.md file we've been using since I
took over maintenance. Ironically, the actual original author has
resurfaced. OctoPrint then offered an upgrade to the installed plugin so it
must have been the correct action. No?

**Comment by gruvin** [comment]
Also, best I can tell, ONLY webcamtab_g.md shows up in the official
registry.

I have no access to Sven's github either.

Still confused.

**Comment by cp2004** [comment]
There is no webcamtab_g.md in this repository, this PR is adding it. You adopted the plugin already in December 2020 (https://github.com/OctoPrint/plugins.octoprint.org/pull/706) updating the original file.

**Comment by gruvin** [comment]
Well that's weird because I did a fresh clone of the entire plugins repo and just edited the existing `webcamtab_g.md` file, after looking at `webcamtab.md` and seeing that is had older, incorrect information. :/ Still confused, sorry.

The plugin repo website is listing some weird mix of not the old or the new description. (Not sure if that's under your wing or not.)

**Comment by gruvin** [comment]
Wow. OK. I see that you are right. (Go figure.) How in the heck did that happen then? I'll redo it. Sorry.

**Pull request closed without merging**
