### PR TITLE
Add plugin ups

### PR DESCRIPTION
**Pull request by kantlivelong**
:wave:

### CODE REVIEW

**Comment by kantlivelong** [comment]
Don't merge yet. Need to add OP version.

**Comment by jneilliii** [comment]
@kantlivelong we prefer to include the images as part of the PR and not reference to GitHub directly for GDPR related reasons...

**Comment by kantlivelong** [comment]
Ah doh old habbit. I'll adjust it.

**Comment by cp2004** [comment]
Preview URL (manually updated) https://cp2004-plugins-octoprint-org-git-pr-931-cp2004.vercel.app/

**Review by jneilliii — APPROVED** [review]

**Pull request merged**
