### PR TITLE
Add Octolapse plugin v0.2.2

### PR DESCRIPTION
**Pull request by FormerLurker**
A single commit pull request for Octolapse .  Thanks for all your help!

### CODE REVIEW

**Comment by kantlivelong** [comment]
#176

**Comment by foosel** [comment]
@FormerLurker I noticed you've set the date to tomorrow (March 24th) instead of today (March 23rd). Confused me a bit since I was making a quick local test myself and the whole listing didn't show up :D Any reason why you've set it to tomorrow? If that's intentional we'll have to merge tomorrow, otherwise it will be missing on the final page build as well.

**Comment by FormerLurker** [comment]
Yes it was intended. When I tried locally it acted like a 'date to
release', but I guess I missed something. I'm out today so I figured
tomorrow would be a good day to drop.  I didn't realize it messed up your
build!? No problem to wait until tomorrow.

**Comment by FormerLurker** [comment]
Ok, thanks!  Have a great weekend away!

**Comment by FormerLurker** [comment]
Thanks kantlivelong!

**Comment by kantlivelong** [comment]
No prob

**Pull request merged**
