### PR TITLE
Added BTT TFT Touchscreen support plugin

### PR DESCRIPTION
**Pull request by jounathaen**
Thanks for all the work of creating OctoPrint! :heart:  :octopus:

### CODE REVIEW

**Comment by jneilliii** [comment]
Notice this utilizes host action commands for start, pause, resume functionality, which means it requires firmware that supports that with very specific messages. You might want to document what firmware that is?

**Comment by jounathaen** [comment]
Hmm, I thought that this was clear enough, but my perspective is obviously biased. Maybe you have some hints on how to enhance this aspect? Probably it is not clear enough, that this line refers to a firmware, not a hardware:

So instead of:

> This plugin adds support for the remote printing features of the [BigTreeTech TFT Touchscreen](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware) for [OctoPrint](https://github.com/OctoPrint/OctoPrint).

maybe this?

> This plugin adds support for the remote printing features of the [BigTreeTech TFT Touchscreen firmware](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware) for [OctoPrint](https://github.com/OctoPrint/OctoPrint).

**Comment by jneilliii** [comment]
> Hmm, I thought that this was clear enough, but my perspective is obviously biased. Maybe you have some hints on how to enhance this aspect? Probably it is not clear enough, that this line refers to a firmware, not a hardware:
> 
> So instead of:
> 
> > This plugin adds support for the remote printing features of the [BigTreeTech TFT Touchscreen](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware) for [OctoPrint](https://github.com/OctoPrint/OctoPrint).
> 
> maybe this?
> 
> > This plugin adds support for the remote printing features of the [BigTreeTech TFT Touchscreen firmware](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware) for [OctoPrint](https://github.com/OctoPrint/OctoPrint).

yeah, that helps a little bit. I think my confusion is probably from the different modes for that firmware, touch vs marlin mode.

**Comment by jounathaen** [comment]
I hope that it's clearer now :slightly_smiling_face:

**Review by jneilliii — APPROVED** [review]

**Pull request merged**
