### PR TITLE
Added plugin SimpleEmergencyStop

### PR DESCRIPTION
**Pull request by BrokenFire**

### CODE REVIEW

**Comment by foosel** [comment]
👍

**Comment by BrokenFire** [comment]
I just have a little question, for update, i just need do a release on GitHub and change version number number on setup.py?

**Comment by foosel** [comment]
No - the plugin repository doesn't know or care about your version number, that's the job of the Software Update plugin once your plugin is installed :)

Just prepare your update, tag it and publish it as a [release on Github](https://help.github.com/articles/creating-releases/). Your tag and the name should be the new version number. OctoPrint's Software Update plugin will take care of the rest on instances your plugin is installed at.

**Comment by BrokenFire** [comment]
Ok thanks! ;)

**Pull request merged**
