### PR TITLE
Add PrettyGCode plugin to repository

### PR DESCRIPTION
**Pull request by Kragrathea**

### CODE REVIEW

**Comment by jneilliii** [comment]
Thanks @Kragrathea I've been looking forward to accepting this plugin. As soon as the checks pass we'll be ready to go.

**Comment by jneilliii** [comment]
Looks like the validate failed on an unrelated plugin. I will review.

**Comment by Kragrathea** [comment]
Ah. I was wondering... Thanks Jneilliii!

**Comment by jneilliii** [comment]
One request. Please update your repos readme so It's not just blank when people go to it. You can just copy/paste the part below the template from this md file over.

**Comment by jneilliii** [comment]
and update the links back to your github repo of course.

**Comment by Kragrathea** [comment]
I updated the readme.md. But I am not sure what links should I update?

**Comment by jneilliii** [comment]
Perfect, you're all good. It's been merged.

**Pull request merged**
