### PR TITLE
googledrivebackup

### PR DESCRIPTION
**Pull request by jneilliii**
update python compatibility

### CODE REVIEW

**Review by foosel — APPROVED** [review]

**Comment by cp2004** [comment]
Make sure you pin it in setup.py as well, so that it prevents people installing it.

**Comment by jneilliii** [comment]
wow, didn't even get to wait for the checks to pass...

**Comment by jneilliii** [comment]
I did @cp2004

**Comment by jneilliii** [comment]
Oh wait, I did it in init.py. There's a way to do it in setup.py?

**Comment by cp2004** [comment]
By specifying `python_requires` in setup.py, the plugin prevents install. For people on Python 2 installs, it prevents the upgrade if the Python version is incompatible, before it even reaches installing. You avoid the 'update broken the install, please fix' issues.

```diff
- additonal_setup_parameters = {}
+ additional_setup_paramters = {"python_requires": ">=3, <4"}
```

**Comment by jneilliii** [comment]
awesome, thanks so much.

**Pull request merged**
