### PR TITLE
Added plugin gslc

### PR DESCRIPTION
**Pull request by Skiepp**
Created a new plugin for Laser Engraving.
For any problem, please refer skiepp93@hotmail.it

Best regards, Skiepp

### CODE REVIEW

**Comment by foosel** [comment]
Hey there, I took a look at your plugin's source and spotted a few problems:

  * [Your update configuration](https://github.com/Skiepp/GCodeSuperLaserController/blob/4e88e2011d22fa412c5339911df62cf90cacabcd/octoprint_GSLC/__init__.py#L66-L72) is incomplete and also uses the wrong identifier (`` instead of ``).
  * [You recompile a regex on every single line queued](https://github.com/Skiepp/GCodeSuperLaserController/blob/4e88e2011d22fa412c5339911df62cf90cacabcd/octoprint_GSLC/__init__.py#L27). That is computational overhead that really should be avoided as it might negatively impact performance. Compile the regex once and then reuse it. Additionally the information that you extract via this regex is already provided to your hook handler in the `gcode` parameter.

Could you fix these issues and then ping me here so that I can look into finalizing the registration? Cheers!

**Comment by Skiepp** [comment]
Hi Gina,

Thanks for the tips! 🙂 I just committed the requested edits.
Coud you please check the section get_update_information?

I'm not entirely sure to have filled it correctly.

Thanks a lot,
Skiepp

________________________________
Da: Gina Häußge <notifications@github.com>
Inviato: mercoledì 4 settembre 2019 14:53
A: OctoPrint/plugins.octoprint.org <plugins.octoprint.org@noreply.github.com>
Cc: Skiepp <skiepp93@hotmail.it>; Author <author@noreply.github.com>
Oggetto: Re: [OctoPrint/plugins.octoprint.org] Added plugin gslc (#342)


Hey there, I took a look at your plugin's source and spotted a few problems:

  *   Your update configuration<https://github.com/Skiepp/GCodeSuperLaserController/blob/4e88e2011d22fa412c5339911df62cf90cacabcd/octoprint_GSLC/__init__.py#L66-L72> is incomplete and also uses the wrong identifier (instead of).
  *   You recompile a regex on every single line queued<https://github.com/Skiepp/GCodeSuperLaserController/blob/4e88e2011d22fa412c5339911df62cf90cacabcd/octoprint_GSLC/__init__.py#L27>. That is computational overhead that really should be avoided as it might negatively impact performance. Compile the regex once and then reuse it. Additionally the information that you extract via this regex is already provided to your hook handler in the gcode parameter.

Could you fix these issues and then ping me here so that I can look into finalizing the registration? Cheers!

**Comment by foosel** [comment]
> Coud you please check the section get_update_information?

https://github.com/Skiepp/GCodeSuperLaserController/blob/master/octoprint_GSLC/__init__.py#L75

```
pip="https://github.com/Skiepp/GCodeSuperLaserController/archive/master.zip"
```

should instead be

```
pip="https://github.com/Skiepp/GCodeSuperLaserController/archive/{target_version}.zip"
```

(`{target_version}` is also supported).

And you are still using the wrong identifier. In `setup.py` you've told OctoPrint that your plugin's identifier is `GSLC`. You also need to use that everywhere else in your code where your plugin's identifier is needed, e.g. [this line](https://github.com/Skiepp/GCodeSuperLaserController/blame/master/octoprint_GSLC/__init__.py#L66), where you use `GCodeSuperLaserController` instead. Whole config should be:

``` python
    def get_update_information(self):
        return dict(
            GSLC=dict(
                displayName="GSLC",
                displayVersion=self._plugin_version,

                type="github_release",
                current=self._plugin_version,
                user="Skiepp",
                repo="GCodeSuperLaserController",

                pip="https://github.com/Skiepp/GCodeSuperLaserController/archive/{target}.zip"
            )
        )
```

See also [the docs](http://docs.octoprint.org/en/master/bundledplugins/softwareupdate.html). The plugin wizard should actually have pregenerated that snippet for you, if you used it.

**Comment by Skiepp** [comment]
Ok! I made the changes you suggested.

Sorry for wasting your time, I'd should have checked the documentation more accurately.

Thanks a lot

**Comment by foosel** [comment]
Looking good now, thanks! 👍

**Pull request merged**
