### PR TITLE
Add wake on lan plugin

### PR DESCRIPTION
**Pull request by Aridor2003**
This pull request adds the Wake-on-LAN plugin to the OctoPrint Plugin Repository. The plugin allows users to send Wake-on-LAN packets to wake up networked devices. Here are the details:
- Repository: https://github.com/Aridor2003/OctoPrint-Wakeonlan
- Author: Aridor Joskowich
- Email: aridor.j@gmail.com
- Compatibility: OctoPrint >= 1.3.0, Python >= 3.6
- License: AGPLv3
- Tags: network, utility

### CODE REVIEW

**Comment by jneilliii** [comment]
I've updated the listing to include the readme details. One last thing, is your plugin needs to have a release tagged 0.1.0 created on its repo to match the version in setup.py. In future updates, when you create a new version, update it in setup.py and create a new tagged release that matches the version number and that's how the users will receive update notifications. 

One last thing, you sure you don't want to include a screenshot of the plugin's navbar button and/or settings? I can assist with adding it if you want.

**Comment by Aridor2003** [comment]
> plugin needs to have a release tagged 0.1.0 created on its repo to match the version in setup.py. 

Will do.

> One last thing, you sure you don't want to include a screenshot of the plugin's navbar button and/or settings? I can assist with adding it if you want. 

Thanks, Where do I include the screenshots?

**Comment by Aridor2003** [comment]
> One last thing, you sure you don't want to include a screenshot of the plugin's navbar button and/or settings? I can assist with adding it if you want. 

I created a folder at https://github.com/Aridor2003/OctoPrint-Wakeonlan/tree/main/raw/master/screenshots with a navbar and setting screenshots

**Comment by jneilliii** [comment]
I've cleaned things up and getting them ready to merge. When you create your new release tagged 0.1.0 (https://github.com/Aridor2003/OctoPrint-Wakeonlan/releases), please delete the `__pycache__` folder first under octoprint_wakeonlan. You shouldn't distribute compiled code as part of the repo.

**Comment by Aridor2003** [comment]
I deleted the `__pycache__` folder and published a new release

**Pull request merged**
