### PR TITLE
The Spaghetti Detective plugin comes out of beta

### PR DESCRIPTION
**Pull request by kennethjiang**
The Spaghetti Detective is coming out of beta. This PR is to add the plugin for the public release, and remove the beta plugin so that the users won't install the wrong one.

### CODE REVIEW

**Comment by kennethjiang** [comment]
Not sure why travis-ci failed. I ran the same command
`bundle exec htmlproofer ./_site --only-4xx --check-favicon --check-html --url-ignore "/ifttt\.com\/polar3d/","/patreon\.com\/join\/FormerLurker/","/tams\.informatik\.uni-hamburg\.de\/research\/3d-printing\/conductive_printing\/index\.html/" --file-ignore "/\.\/_site\/search\/index\.php/","/\.\/_site\/by_(author|tag|date|name)\/index\.html/" --log-level ':debug'` and it worked on my laptop.

**Comment by kennethjiang** [comment]
Fixed it. Somehow the release date would cause build to fail... who knew. :)

**Comment by foosel** [comment]
> Fixed it. Somehow the release date would cause build to fail... who knew. :)

How odd... 🤔

**Comment by kennethjiang** [comment]
Thank you so much @foosel for your prompt action!

**Pull request merged**
