### PR TITLE
Integrating Octoslack into plugin repository

### PR DESCRIPTION
**Pull request by fraschetti**

### CODE REVIEW

**Comment by foosel** [comment]
Took a quick look, could you protect the sensitive information stored in the settings (especially the API tokens) via [`get_settings_restricted_paths`](http://docs.octoprint.org/en/master/plugins/mixins.html#octoprint.plugin.SettingsPlugin.get_settings_restricted_paths)? :)

**Comment by foosel** [comment]
@fraschetti I accidentally merged this even though I'm still waiting for feedback re the aforementioned sensitive settings. I've marked the plugin as disabled temporarily until this is taken care of, please give me a ping when that is resolved (or if you have questions)! Sorry for the hassle.

**Comment by fraschetti** [comment]
@foosel I've pushed a new release with the get_settings_restricted_paths addition. On a related note, the documentation for get_settings_restricted_paths has a typo; an example is missing the s on paths.

http://docs.octoprint.org/en/master/plugins/mixins.html#octoprint.plugin.SettingsPlugin.get_settings_restricted_paths
```
def get_settings_restricted_path(self):
    return dict(admin=[["some", "admin_only", "path"], ["another", "admin_only", "path"],
                user=[["some", "user_only", "path"],],
                never=[["path", "to", "never", "return"],])
```

**Comment by foosel** [comment]
@fraschetti perfect, re-enabled. Also thanks for the hint about the typo, fixed in [this commit](https://github.com/foosel/OctoPrint/commit/557c761e805d1096e584701157aa5dd1050ab02c).

**Pull request merged**
