### PR TITLE
Added plugin mmu2filamentselect

### PR DESCRIPTION
**Pull request by derpicknicker1**
A plugin to control the filament selection on prusa mmu2 printers. If a file is sliced in singel filament mode, the printer asks for user interaction to choose the desired filament. This plugin will instead bring up an Dialog in octoprint to let the user choose the filament without heading to the printer.

### CODE REVIEW

**Comment by foosel** [comment]
Is it intentional that you left out update capabilities?

**Comment by derpicknicker1** [comment]
There are update capabilities.
See https://github.com/derpicknicker1/OctoPrint-Mmu2filamentselect/blob/master/octoprint_mmu2filamentselect/__init__.py#L105

**Comment by foosel** [comment]
Did you forget to push that? That definitely was not there earlier 🤔 Anyhow, that configuration uses the wrong identifier, `updateplugindemo` instead of `mmu2filamentselect`. You might want to fix that before I merge this.

**Comment by derpicknicker1** [comment]
It must have been pushed because the code was in the release zip file 🤔 Or am i wrong?
I fixed the update now.
Thanks for the review. It was a bit hard for me to publish my first plugin from scratch at 5am 😅
Until now i only worked on existing plugins.

**Comment by foosel** [comment]
> It must have been pushed because the code was in the release zip file 🤔 Or am i wrong?

Nah, you are right. Weird... I definitely didn't see it, and I double checked the hooks explicitly. Ghosts? Aliens? It is a mystery...

> Thanks for the review. It was a bit hard for me to publish my first plugin from scratch at 5am 😅

Up late or early? 😂

**Comment by derpicknicker1** [comment]
Late 😬I had spare time the first time since over a year for coding at night🎉

**Pull request merged**
