### PR TITLE
Updated OctoLight API information

### PR DESCRIPTION
**Pull request by thomst08**
- Updated OctoLight API information
- Added notification regarding older version of OctoLight as it changes the API

Please let me know if this is not a good use of the ``notices`` file as I am OK if it shouldn't be used in this way.
Thank you.

### CODE REVIEW

**Comment by cp2004** [comment]
Would it be easier to keep the API documentation just on your plugin's GitHub readme, and just provide a link from the plugin repository? That should save you making lots of PRs here if you want to change the docs (even small corrections you might find) in the future?

**Comment by thomst08** [comment]
Honestly, I don't see it changing much beyond this but you have a point, if you would prefer I do that then let me know and I will change the file straight way.

**Comment by thomst08** [comment]
@cp2004, thanks for the suggestion, thinking about it, I think you have a point.  The change is done.

**Comment by jneilliii** [comment]
hmm...we've never had plugin notices outside of plugin adoption ones before. Need @foosel input on this one.

**Comment by thomst08** [comment]
Sorry for the delay, I removed the notification addition.
Sorry for causing any issues.

**Review by jneilliii — APPROVED** [review]

**Pull request merged**
