### PR TITLE
Plugin meatpack - update description w/ less dynamic information.

### PR DESCRIPTION
**Pull request by scottmudge**
Updated description with more general description and a link to an external list of supported firmware. Also updated compression ratio with latest numbers.

### CODE REVIEW

**Review by jneilliii — APPROVED** [review]

**Comment by scottmudge** [comment]
@jneilliii Thanks, one last question -- this line in the plugin's descriptor/md file:

`python: ">=2.7,<4"`

This plugin is only compatible with python >= 3.7. Should I change it to:

`python: ">=3.7,<4"` 

?

**Comment by scottmudge** [comment]
Nevermind, I'll just make it more compatible. Makes the most sense.

**Comment by cp2004** [comment]
They should match, so that people know before installing. It can be quite a lot of effort to go back to Python 2 - I wouldn't recommend it. OctoPi 0.18 is out with Python 3, over 15% of installs (and rising quicker now, watch https://data.octoprint.org/).

**Comment by jneilliii** [comment]
I agree, force it to python 3 only and just submit a PR to update here.

**Comment by foosel** [comment]
Just to chime in: yep, focus on py3. I wish I didn't have to still support 2, be glad if you don't ;)

**Comment by scottmudge** [comment]
Alright, so I made multiple notes in the release notes and README that it's highly recommended to update to Python 3, but given it only required minor syntax changes, it should in theory be compatible back to 2.7.

Not that I *want* to support it moving forward, but I figured most of the older systems which might see the most benefit from g-code compression are still running 2.7, and a lot of people (unfortunately) aren't going to bother manually upgrading to Python 3.

**Comment by scottmudge** [comment]
One last question, how often does the plugin repository pull update information from the associated plugins' repos? If I publish a new release, will it take a few hours to be reflected in the Plugin Repository?

**Comment by cp2004** [comment]
Every 12 hours, at midnight/midday UTC. Or the build also runs when a PR is merged.

**Comment by scottmudge** [comment]
Great, good to know. Thanks!

**Pull request merged**
