### PR TITLE
GPX plugin, update configuration instructions

### PR DESCRIPTION
**Pull request by markwal**
GPX plugin now has an editor for gpx.ini so the configuration is easier

### CODE REVIEW

**Comment by markwal** [comment]
This is just the description update.  I got the id update tangled up with trying to change the url.  I'll push that one later today after I test it.

**Comment by foosel** [comment]
Do you want me to merge that one now or wait for the id change push?

**Comment by markwal** [comment]
Lets wait and get it in one go. Sorry, I'd forgot that change when I made the PR.

Sent from my Windows Phone
________________________________

**Comment by markwal** [comment]
Pretty simple change, but I needed to find a moment to get jekyll up and running and redirect my config.yaml so I could verify "reinstall".

**Pull request merged**
