### PR TITLE
Added plugin physicalbutton

### PR DESCRIPTION
**Pull request by LuxuSam**
Hi guys,

I wrote a plugin which lets you connect physical buttons to a raspberry pi to send GCODE and actions to OctoPrint. 😁

### CODE REVIEW

**Comment by cp2004** [comment]
Experimental preview deployment, manually updated: https://cp2004-plugins-octoprint-org-git-pr-923-cp2004.vercel.app/

**Review by jneilliii — CHANGES_REQUESTED** [review]
Nice plugin. Initial look appears to be everything in order. I added the os compatibility back in. the build checks are unrelated to your PR. wonder why gitignore was changed?

One issue on your plugin side, python compatibility flag varies from the plugin repo listing [here](https://github.com/LuxuSam/PhysicalButton/blob/8f1fa9f5cf589ed4d0aff2c64f0d5d8109b7031f/octoprint_physicalbutton/__init__.py#L177).

**Comment by jneilliii** [comment]
> Experimental preview deployment, manually updated: https://cp2004-plugins-octoprint-org-git-pr-923-cp2004.vercel.app/

nice @cp2004

**Comment by LuxuSam** [comment]
> Nice plugin. Initial look appears to be everything in order. I added the os compatibility back in. the build checks are unrelated to your PR. wonder why gitignore was changed?
> 
> One issue on your plugin side, python compatibility flag varies from the plugin repo listing [here](https://github.com/LuxuSam/PhysicalButton/blob/8f1fa9f5cf589ed4d0aff2c64f0d5d8109b7031f/octoprint_physicalbutton/__init__.py#L177).

I changed the gitignore so .jekyll-metadata .bundle are ignored but actually did not want to push that 😅

True, sorry I knew there was one more spot where I had to change the Python version

**Comment by LuxuSam** [comment]
I also corrected the python compatibility flag :)

**Review by jneilliii — APPROVED** [review]

**Pull request merged**
