### PR TITLE
Text about succeeding OctoPrint Anywhere with The Spaghetti Detective

### PR DESCRIPTION
**Pull request by kennethjiang**
As previously communicated I plan to completely replace OctoPrint Anywhere with The Spaghetti Detective.

### CODE REVIEW

**Comment by kennethjiang** [comment]
As previously communicated I plan to completely replace OctoPrint Anywhere with The Spaghetti Detective.

**Comment by foosel** [comment]
No problem with that, but can you keep the CSS shenanigans to a minimum (e.g. style attributes in this case)? I want to avoid potential conflicts with future site changes.

**Comment by kennethjiang** [comment]
> No problem with that, but can you keep the CSS shenanigans to a minimum (e.g. style attributes in this case)? I want to avoid potential conflicts with future site changes.

Done. Inline style can't do hover effect but it's definitely just nice to have.

**Comment by foosel** [comment]
Perfect, thank you!

**Pull request merged**
